services:
  mysqldb:
    image: mysql
    container_name: sqldb
    restart: always
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=dm
      - MYSQL_PASSWORD=dmpass 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysqldb
    depends_on:
      - mysqldb      
  scrapper:
    build: 
      context: ./scrapper
    container_name: scrapper
    #restart: always
    depends_on:
      - mysqldb
  api_site:
    build: 
      context: ./api_site
    container_name: api_site
    ports:
      - 8501:8501
    #restart: always
    depends_on:
      - mysqldb
